export { default as TestmonialCard } from './testmonial'
export { default as TestmonialCard1 } from './testimonial1'
export { default as TestmonialCard2 } from './testimonial2'
export { default as TestmonialCard3 } from './testimonial3'
export { default as TestmonialCard4 } from './testimonial4'
